Add Sarra Ben Arbia profile to multi site
multi-coop/multi-site-contents pull request #83
Opened 2024-03-13 16:48 UTC by Sarrabah

J'ai ajouté ma biographie sur le site.

2024-03-13 16:58 UTC, pierrecamilleri commented on texts/team/people/Sarra-Ben-Arbia.md
> +email: sarra.banarbia@multi.coop
```suggestion
email: sarra.benarbia@multi.coop
```

2024-03-13 16:58 UTC, pierrecamilleri commented on texts/team/people/Sarra-Ben-Arbia.md
> +status: [ apprentice ]
Je pense que comme c'est la première fois que l'occasion se présente, il faudra renseigner la traduction qqpart (pas le temps maintenant, mais je peux m'en occuper plus tard)

2024-03-14 08:57 UTC, pierrecamilleri commented on texts/team/people/Sarra-Ben-Arbia.md
> +status: [ apprentice ]
Done

2024-03-14 16:56 UTC, JulienParis requested changes

2024-03-14 16:56 UTC, JulienParis commented on texts/team/team-data.md
> +  apprendtice:
Ah il y a une petite typo ici : `apprentice` à mettre plutôt que `apprendtice`

2024-03-15 08:42 UTC, pierrecamilleri commented on texts/team/team-data.md
> +  apprendtice:
Bien vu, c'est moi qui l'ai introduite, c'est corrigé.

2024-03-18 12:47 UTC, merged